
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urgposyuzwyncahuuukd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyZ3Bvc3l1end5bmNhaHV1dWtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2OTMxMzQsImV4cCI6MjA2MzI2OTEzNH0.qeikYJPnIRH8Rr5WLUeOTfHIOyFw-vIR8i4rana6zSM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
