// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Configuração sincronizada com o sistema principal (closetfesta)
const SUPABASE_URL = "https://gxquifexgzckttkkhwhk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4cXVpZmV4Z3pja3R0a2tod2hrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NTExMjAsImV4cCI6MjA2MTQyNzEyMH0.kwAU_2H2EQWA31m-1ogeaVtdlbJOXzPcz35IWK79MXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
